### ISSUE TITLE
Cool to have default times(1) inside verify

### ISSUE THREAD

**Issue by danielgomezrico** [paslavsky/mockito-kt#1]
Will be great to have the option to not use times(1).. just to avoid a lot of times(1) all over the place

Instead of:

```
       verify(mockedView) {
            times(1).initViews()
            times(1).setImage(user.photoUrl)
        }
```

have 

```
       verify(mockedView) {
            initViews()
            setImage(user.photoUrl)
        }
```

**Comment by paslavskyi** [comment]
@danielgomezrico I will think about this

**Comment by danielgomezrico** [comment]
@paslavsky check https://github.com/paslavsky/mockito-kt/pull/2

**Comment by paslavskyi** [comment]
@danielgomezrico Please check new version 
https://github.com/paslavsky/mockito-kt/releases/tag/0.0.5-beta
I added new method `once`:

```
// Mocking
val mockService = mock(serviceClass)
// Test
mockService.foo()
mockService.bar(SomeData("Test", 1))
// Verification
once(mockService) { match ->
    foo()
    bar(match.eq(SomeData("Test", 1)))
}
```

**Comment by danielgomezrico** [comment]
can it be called `verifyOne()` just to continue with mockito names?

**Comment by paslavskyi** [comment]
Agree

**Comment by paslavskyi** [comment]
Done
