### ISSUE TITLE
Could not resolve mockito kt on maven repository

### ISSUE THREAD

**Issue by danielgomezrico** [paslavsky/mockito-kt#3]
Hi, Im getting:

```
    > Could not resolve net.paslavsky.kotlin:mockito-kt:0.0.4-beta.
         > Could not get resource 'http://paslavsky.homeunix.net:8000/nexus/content/repositories/releases/net/paslavsky/kotlin/mockito-kt/0.0.4-beta/mockito-kt-0.0.4-beta.pom'.
            > Could not HEAD 'http://paslavsky.homeunix.net:8000/nexus/content/repositories/releases/net/paslavsky/kotlin/mockito-kt/0.0.4-beta/mockito-kt-0.0.4-beta.pom'. Received status code 503 from server: Ser
```

why?

**Comment by danielgomezrico** [comment]
I downloaded the jar and import it with `testCompile files('libs/mockito-kt-0.0.4-beta.jar')` and it works fine.

**Comment by paslavskyi** [comment]
I apologize for the inconvenience
Looks like some problems with my local nexus repo. I will re-check

**Comment by paslavskyi** [comment]
@danielgomezrico Please recheck
I fixed problem with routes

**Comment by K0zka** [comment]
@paslavsky could you upload this artifact to a public repository like maven-central or bintray?

**Comment by paslavskyi** [comment]
Now it available on BinTray: https://bintray.com/paslavsky/maven/mockito-kt
